import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/landing/site-header";
import { getCaseStudies, getCaseStudy } from "@/lib/cms";
import { getSiteUrl } from "@/lib/env";

export async function generateStaticParams() { return (await getCaseStudies()).map((study) => ({ slug: study.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const study = await getCaseStudy((await params).slug); if (!study) return {}; const url = `${getSiteUrl()}/case-studies/${study.slug}`; const title = study.seo_title ?? study.title; const description = study.seo_description ?? study.results; return { title, description, alternates: { canonical: url }, openGraph: { title, description, url, type: "article", images: study.featured_image_url ? [study.featured_image_url] : [] }, twitter: { card: "summary_large_image", title, description } }; }
export default async function CaseStudyPage({ params }: { params: Promise<{ slug: string }> }) { const study = await getCaseStudy((await params).slug); if (!study) notFound(); const jsonLd = { "@context": "https://schema.org", "@type": "Article", headline: study.title, about: study.industry, datePublished: study.published_at, mainEntityOfPage: `${getSiteUrl()}/case-studies/${study.slug}` }; return <><SiteHeader /><main className="container-page max-w-4xl py-12"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><p className="text-sm font-semibold text-primary">{study.industry} case study</p><h1 className="mt-3 text-4xl font-bold">{study.title}</h1><p className="mt-3 text-muted-foreground">Customer: {study.customer}</p><div className="mt-8 grid gap-4 md:grid-cols-3"><Section title="Challenge" text={study.challenge} /><Section title="Solution" text={study.solution} /><Section title="Results" text={study.results} /></div></main></>; }
function Section({ title, text }: { title: string; text: string }) { return <section className="rounded-lg border bg-card p-5"><h2 className="font-semibold">{title}</h2><p className="mt-3 text-sm text-muted-foreground">{text}</p></section>; }
