import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/landing/site-header";
import { getBlogPost, getBlogPosts } from "@/lib/cms";
import { getSiteUrl } from "@/lib/env";

export async function generateStaticParams() { return (await getBlogPosts()).map((post) => ({ slug: post.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const post = await getBlogPost((await params).slug); if (!post) return {}; const url = `${getSiteUrl()}/blog/${post.slug}`; const title = post.seo_title ?? post.title; const description = post.seo_description ?? post.excerpt; return { title, description, alternates: { canonical: url }, openGraph: { title, description, url, type: "article", publishedTime: post.published_at, authors: [post.author], images: post.featured_image_url ? [post.featured_image_url] : [] }, twitter: { card: "summary_large_image", title, description } }; }
export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) { const post = await getBlogPost((await params).slug); if (!post) notFound(); const url = `${getSiteUrl()}/blog/${post.slug}`; const articleJsonLd = { "@context": "https://schema.org", "@type": "Article", headline: post.title, description: post.excerpt, author: { "@type": "Organization", name: post.author }, datePublished: post.published_at, mainEntityOfPage: url, keywords: post.tags.join(", ") }; return <><SiteHeader /><main className="container-page max-w-3xl py-12"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }} /><p className="text-sm font-semibold text-primary">{post.category}</p><h1 className="mt-3 text-4xl font-bold">{post.title}</h1><p className="mt-3 text-muted-foreground">By {post.author} • {new Date(post.published_at).toLocaleDateString()}</p><div className="mt-6 flex flex-wrap gap-2">{post.tags.map((tag) => <span key={tag} className="rounded-full bg-secondary px-3 py-1 text-xs font-medium">{tag}</span>)}</div><article className="prose prose-neutral mt-8 max-w-none"><p>{post.content}</p></article></main></>; }
